Configurate linters.
taher-software/Hello-Microverse pull request #1
Opened 2021-09-14 20:31 UTC by Taher-web-dev

2021-09-14 21:31 UTC, DanteAlonsoHT requested changes
<h1> Status: Required Changes 🚫 🔴 </h1>

Hi @Taher-web-dev,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] Improve the description in your Pull Request, explain what you did, what is the main scope, which files do you changed or added, what you set up in your project in this pull request, and so on.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-14 21:31 UTC, DanteAlonsoHT commented on README.md
> +
- [ ] You can remove this empty section.

2021-09-14 21:31 UTC, DanteAlonsoHT commented on README.md
> +
- [ ] [OPTIONAL] For the next time try to add more instructions about how to set up your project in any local environment, check [This Example](https://github.com/DanteAlonsoHT/Leaderboard_API) to let you know what we expect from students 😉

2021-09-14 21:31 UTC, DanteAlonsoHT commented on txt.tx
> -This is my first project !
- [ ] I feel this is your `test.md`, please if it's that case, please re-named to `test.md` and remove it from your Github repository.

2021-09-15 08:17 UTC, dasileker approved these changes
## **Hi @Taher-web-dev**

## **Project Approved ✅**



Your project is complete!  There is nothing else to say other than... it's time to merge it 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-15 11:36 UTC, merged